version: '3.1'

services:
  
  www:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes: 
      - ./:/var/www/html
      
  adminer: 
    image: adminer:latest
    restart: always
    ports: 
      - 8081:8080
    depends_on:
      - db
    
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: animus12
    volumes: 
      - ./db:/var/lib/mysql
